trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build the project'

- script: |
    npm test
  displayName: 'Run tests'

# Optionally add linting
- script: |
    npm run lint
  displayName: 'Lint the code'

# Deployment step (adjust based on your deployment target)
- script: |
    npm run export
  displayName: 'Export the project for deployment'

# For example, deploying to Azure Static Web Apps
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/' 
    output_location: 'out' # Set this to where your build outputs are located
  displayName: 'Deploy to Azure Static Web Apps'

# Add more steps as needed for things like caching, notifications, etc.
